/**
 * Official Icon System Foundation for Islamic University Events Platform.
 * All icons across the system must use `@tabler/icons-react`.
 * DO NOT add new emoji-based icons.
 */

export {
    IconCalendar,
    IconCalendarEvent,
    IconCalendarPlus,
    IconCalendarRepeat,
    IconMapPin,
    IconClock,
    IconTicket,
    IconUsers,
    IconUser,
    IconUserPlus,
    IconCheck,
    IconAlertCircle,
    IconAlertTriangle,
    IconInfoCircle,
    IconChevronDown,
    IconChevronLeft,
    IconChevronRight,
    IconChevronUp,
    IconArrowRight,
    IconArrowLeft,
    IconSearch,
    IconBuilding,
    IconSettings,
    IconLogout,
    IconDownload,
    IconShare,
    IconMail,
    IconMailCheck,
    IconSend,
    IconCopy,
    IconCopyPlus,
    IconPencil,
    IconTrash,
    IconPlus,
    IconX,
    IconFilter,
    IconQrcode,
    IconEye,
    IconEyeOff,
    IconLock,
    IconDotsVertical,
    IconHome,
    IconSparkles,
    IconPackage,
    IconReceipt,
    IconPrinter,
    IconAward,
    IconFileText,
    IconExternalLink,
} from '@tabler/icons-react';
